version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: ai_chat_redis
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --requirepass !qaz2wsX
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "!qaz2wsX", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:5.0
    container_name: ai_chat_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "mongodb://root:example@localhost:27017/admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
  mongodb_data: