"""
配置模块 - 包含应用程序的各种配置和默认值
"""

# 从memory_settings.py导入所有配置
from app.config.memory_settings import (
    MEMORY_CONFIG,
    VECTOR_STORE_CONFIG,
    MEMORY_WORKFLOW,
    MEMORY_TYPES,
    REDIS_HOST,
    REDIS_PORT,
    REDIS_PASSWORD,
    REDIS_DB,
    MAX_CHAT_ROUNDS,
    SUMMARY_MODEL,
    SUMMARY_MAX_TOKENS,
    SUMMARY_TEMPERATURE,
    SUMMARY_PROMPT_TEMPLATE,
    DEFAULT_SUMMARY,
    MAX_TOKENS
)

# 为了向后兼容，将重要的配置直接暴露在模块级别
memory_settings = {
    # 记忆配置项
    "MEMORY_CONFIG": MEMORY_CONFIG,
    "VECTOR_STORE_CONFIG": VECTOR_STORE_CONFIG,
    "MEMORY_WORKFLOW": MEMORY_WORKFLOW,
    "MEMORY_TYPES": MEMORY_TYPES,
    
    # Redis配置
    "REDIS_HOST": REDIS_HOST,
    "REDIS_PORT": REDIS_PORT,
    "REDIS_PASSWORD": REDIS_PASSWORD,
    "REDIS_DB": REDIS_DB,
    
    # 聊天相关
    "MAX_CHAT_ROUNDS": MAX_CHAT_ROUNDS,
    
    # 摘要相关
    "SUMMARY_MODEL": SUMMARY_MODEL,
    "SUMMARY_MAX_TOKENS": SUMMARY_MAX_TOKENS,
    "SUMMARY_TEMPERATURE": SUMMARY_TEMPERATURE,
    "SUMMARY_PROMPT_TEMPLATE": SUMMARY_PROMPT_TEMPLATE,
    "DEFAULT_SUMMARY": DEFAULT_SUMMARY,
    "MAX_TOKENS": MAX_TOKENS
} 